modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/Streak/issues"

[[mods]]
    modId="streak"
    version="${file.jarVersion}" #mandatory
    displayName="Streak"
    displayURL="https://ichun.me/mods/streak/"
    authors="iChun"
    description='''
    Streak mod, a clientside trail-rendering effect for players.
    '''

[[dependencies.streak]]
    modId="ichunutil"
    mandatory=true
    versionRange="[10.0.0,11)"
    ordering="NONE"
    side="BOTH"
