modLoader="javafml"
loaderVersion="[32,)" #forge version dep
issueTrackerURL="https://github.com/iChun/Streak/issues"

[[mods]]
    modId="streak"
    version="${file.jarVersion}" #mandatory
    displayName="Streak"
    displayURL="https://ichun.me/mods/streak/"
    authors="iChun"
    description='''
    Streak mod, a clientside trail-rendering effect for players.
    '''

[[dependencies.streak]]
    modId="ichunutil"
    mandatory=true
    versionRange="[9.0.0,10)"
    ordering="NONE"
    side="BOTH"
